var chumashim = [
	{"name":"Bereishit", "dir":"mp3/NC/"},
	{"name":"Shemot", "dir":"mp3/NC/"},
	{"name":"Vayikra", "dir":"mp3/NC/"},
	{"name":"Bamidbar", "dir":"mp3/NC/"},
	{"name":"Devarim", "dir":"mp3/NC/"},
	{"name":"Leading Services", "dir":"mp3/chazanus/"},
	{"name":"My Thoughts", "dir":"mp3/thoughts/"}
];
var parashos = {
	"Bereishit": ["Bereishit",
		"Noach",
		"Lech Lecha",
		"Vayeira",
		"Chayei Sarah",
		"Toldot",
		"Vayeitzei",
		"Vayishlach",
		"Vayeishev",
		"Mikeitz",
		"Vayigash",
		"Vayechi"
	],
	"Shemot": ["Shemot",
		"Va'eira",
		"Bo",
		"Beshalach",
		"Yitro",
		"Mishpatim",
		"Terumah",
		"Tetzaveh",
		"Ki Tisa",
		"Vayakhel",
		"Pekudei"
	],
	"Vayikra": ["Vayikra",
		"Tzav",
		"Shemini",
		"Tazria",
		"Metzora",
		"Acharei",
		"Kedoshim",
		"Emor",
		"Behar",
		"Bechukotai"
	],
	"Bamidbar": ["Bamidbar",
		"Naso",
		"Behaalotecha",
		"Shelach",
		"Korach",
		"Chukat",
		"Balak",
		"Pinchas",
		"Matot",
		"Massei"
	],
	"Devarim": ["Devarim",
		"Va'etchanan",
		"Eikev",
		"Re'eh",
		"Shoftim",
		"Ki Teitzei",
		"Ki Tavo",
		"Nitzavim",
		"Vayelech",
		"Haazinu",
		"V'Zot HaBerachah"
	],
	"Leading Services":["Leading Services"],
	"My Thoughts":["My Thoughts"]
};